# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-27 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190220_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
