# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-01 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_anonymous'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='created',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
