# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 05:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_mentor_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='major',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Major'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile'),
        ),
    ]
