# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='verification_code',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
