# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20171108_0410'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.ImageField(null=True, upload_to='profile_pictures/'),
        ),
    ]
