# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='verification_code',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
