# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20171125_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='verification_code',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
