# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20171206_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, default='profile_pictures/default_pic.jpg', null=True, upload_to='profile_pictures/'),
        ),
    ]
