# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-11 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20180110_0108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='mentor',
            options={'ordering': ('profile',)},
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='classes',
        ),
        migrations.AddField(
            model_name='mentor',
            name='classes',
            field=models.ManyToManyField(to='users.Classes'),
        ),
    ]
