# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-08 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20171206_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='major',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
