# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-11 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20180111_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='classes',
            field=models.ManyToManyField(blank=True, to='users.Classes'),
        ),
    ]
