# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-12 20:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20180111_0412'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Classes',
            new_name='Course',
        ),
        migrations.RenameField(
            model_name='mentor',
            old_name='classes',
            new_name='courses',
        ),
    ]
