# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-26 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_merge_20180112_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notification',
            field=models.BooleanField(default=True),
        ),
    ]
