# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-02 22:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_profile_notification'),
        ('users', '0019_auto_20180202_2213'),
    ]

    operations = [
    ]
