# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-04 00:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_merge_20180202_2235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='notification',
            new_name='notifications_enabled',
        ),
    ]
