# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-13 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20180204_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password_reset_code',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
