# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-14 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_profile_password_reset_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='password_reset_code',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, unique=True),
        ),
    ]
