# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-25 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20180324_0125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Minor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='mentor',
            name='minor',
            field=models.ManyToManyField(blank=True, to='users.Minor'),
        ),
    ]
