# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-08 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20180324_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='year',
            field=models.CharField(choices=[('Incoming', 'Incoming'), ('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th+', '5th+')], default='Incoming', max_length=15),
        ),
    ]
