# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-17 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20180417_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='minor',
        ),
        migrations.AddField(
            model_name='mentor',
            name='minor',
            field=models.ManyToManyField(blank=True, to='users.Minor'),
        ),
    ]
