# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-25 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20180425_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='minor',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
