# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-25 22:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20180425_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='minor',
        ),
        migrations.AddField(
            model_name='mentor',
            name='ajor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Minor'),
        ),
    ]
