# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-25 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20180425_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='ajor',
        ),
        migrations.AddField(
            model_name='mentor',
            name='minor',
            field=models.ManyToManyField(blank=True, to='users.Minor'),
        ),
    ]
