# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-17 22:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20180417_2240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='minor',
            options={'ordering': ('name',)},
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='major',
        ),
        migrations.AddField(
            model_name='mentor',
            name='major',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Major'),
        ),
    ]
