# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-24 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20180417_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='courses',
            field=models.ManyToManyField(blank=True, max_length=200, to='users.Course'),
        ),
    ]
