# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-15 10:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20180515_1045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='major',
            options={'ordering': ('name',)},
        ),
    ]
