# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-24 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20180424_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='courses',
            field=models.ManyToManyField(blank=True, to='users.Course'),
        ),
    ]
