# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-04 00:18
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20180508_1121'),
        ('users', '0031_auto_20180521_2123'),
    ]

    operations = [
        TrigramExtension()
    ]
