# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-20 20:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0021_auto_20180204_0040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_1', to='users.Profile')),
                ('profile_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_2', to='users.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='thread',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='messaging.Thread'),
        ),
    ]
