# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-04 03:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20180204_0040'),
        ('messaging', '0002_auto_20180221_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Profile'),
        ),
    ]
